---
title: "Car2Go Diverse Layers"
author: "Myeong Lee"
date: "5/17/2017"
output: html_document
---
This code is for processing and visualizing diverse geospatial polygons and aggregating from one layer to another when polygons are different. 

```{r}
library(ggmap)
library(ggplot2)
library(stringr)
library(readr)
library(dplyr)
library(sp)
library(rgeos)
library(rgdal)
library(raster)
library(classInt)

register_google(key="AIzaSyD36Jq79omYvK4q160enCpKcdzeuhlCu7U")
```


# Extracting Car2go's points data as SpatialPointsDataFrame
```{r}
setwd("~/git/geo-aggregation-carpentry/data/")

total <- read_delim("car2go_samples.csv", delim = ",",col_names = T )
total$ID <- row.names(total)
total$ID <- as.integer(total$ID)
xy <- total[,c("lon","lat")]
points <- SpatialPointsDataFrame(coords = xy, data = total,
                               proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
plot(points)
```

# Loading polygons from KML and Shapefiles + Viz
```{r}

# DC Boundary as a polygon
dc_boundary <- readOGR("DC_Boundary/DC_Boundary.shp") %>% spTransform(CRS("+proj=longlat +datum=WGS84"))
map <- get_map(location = 'Washinton DC', zoom = 11, color = "bw")
mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group), 
                                       data = dc_boundary, color='red', alpha=0) + ggtitle("DC Boundary")
mapPoints

# DC neighborhood boundaries 
gov_cluster <- readOGR("dc_neighborhood_boundaries_GovClusters.kml", 
                       layer="dc_neighborhood_boundaries_GovClusters") %>% 
                      spTransform(CRS("+proj=longlat +datum=WGS84"))

mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group), 
                                       data = gov_cluster, color='red', alpha=0.5) + ggtitle("Gov Clusters")
mapPoints

```


```{r}


for(i in 1:nrow(gov_cluster)) { 
  
  print(i)
  intersection = raster::intersect(x = points, y = gov_cluster[i,])
  if (nrow(intersection@data) == 0) next
  
  freq_table <- intersection@data %>% dplyr::group_by(date) %>% summarise(freq=n())
  freq_table$day <- c("Weekend", "Weekday", "Weekday", "Weekday", "Weekday", "Weekday", "Weekend")[as.POSIXlt(freq_table$date)$wday + 1]
  freq_table$day <- as.factor(freq_table$day)

  weekday <- freq_table[freq_table$day == "Weekday",]
  weekend <- freq_table[freq_table$day == "Weekend",]
  
  weekday$minute <- minute(weekday$date)/60
  weekday$minute[weekday$minute==0.6] <- 35/60
  weekday$time <- hour(weekday$date) + weekday$minute
  weekday <- weekday %>% dplyr::group_by(time) %>% summarise(freq = sum(freq), weekday=1)
  
  weekend$time <- hour(weekend$date) + minute(weekend$date)/60
  weekend <- weekend %>% dplyr::group_by(time) %>% summarise(freq = sum(freq), weekday=0)
    
  temp <- rbind(weekday, weekend)
  temp$id <- i 
  signature <- rbind(signature, temp)

}


## Since the loop takes a long time -- we're loading the result of the loop from a file
# signature <- read_delim("csv/5_min_signature_sum.csv", delim = ",",col_names = TRUE ) 
# signature <- signature[,-1]

hex_grid <- gov_cluster
row.names(hex_grid) <- as.character(1:length(hex_grid))
hex_grid$ID <- row.names(hex_grid)

# region-based time aggregation
time_agg <- signature %>% group_by(id) %>% summarise(freq = sum(freq)/576)
time_agg$id <- as.character(time_agg$id)

hex_grid@data <- hex_grid@data %>% left_join(time_agg, by = c("ID" = "id"))
hex_grid@data$freq[is.na(hex_grid@data$freq)] <- 0

lnd <- SpatialPolygonsDataFrame(Sr = spTransform(hex_grid, CRSobj = CRS("+init=epsg:4326")), data = hex_grid@data)
lnd.f <- fortify(lnd)
lnd$id <- row.names(lnd)
lnd.f <- left_join(lnd.f, lnd@data, by=("id"))
lnd.f$freq[lnd.f$freq == 0] <- 0.0001
# Need a basemap for this -- Density Map

map <- get_map(location = 'Washinton DC', zoom = 11, color = "bw")
mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group, fill=(freq)), data = lnd.f , alpha=0.9) + scale_fill_continuous(low = "yellow", high = "red") + ggtitle("GovCluster Layer")
mapPoints


# Conducting Clustering analysis for the Polygons
# Reshaping the dataframe to make signatures 
library(reshape)
sig_day <- signature[signature$weekday == 1,]
sig_end <- signature[signature$weekday == 0,]

day <- cast(sig_day, id~time, value="freq")
end <- cast(sig_end, id~time, value="freq")

day[is.na(day)] <- 0
end[is.na(end)] <- 0

day_norm <- as.data.frame(t(apply(day[,-1], 1, function(x)  (x-min(x))/(max(x)-min(x)) )))
end_norm <- as.data.frame(t(apply(end[,-1], 1, function(x)  (x-min(x))/(max(x)-min(x)) )))

#Reverting the graphs?
for (i in 1:nrow(day_norm)){
  day_norm[i,] <- apply(day_norm[i,], 1, function(x) 1-x)
}
for (i in 1:nrow(end_norm)){
  end_norm[i,] <- apply(day_norm[i,], 1, function(x) 1-x)
}

day_norm$id <- day$id
end_norm$id <- end$id

final <- data.frame(matrix(ncol=1, nrow=nrow(hex_grid@data)))
colnames(final) <- c ("ID")
final$ID <- c(1:nrow(hex_grid@data))
final <- final %>% left_join(day_norm, by = c("ID" = "id"))
final <- final %>% left_join(end_norm, by = c("ID" = "id"))

normalized <- final
normalized[is.na(normalized)] <- 0

# DBs <- vector(mode="integer", length=10)
# for (i in 1:10) {
#     ks <- kmeans(na.omit(normalized[, 2:ncol(normalized)]), i+2)
#     cls <- data.frame(ks$cluster)
#     row.names(cls) <- na.omit(normalized[, 2:ncol(normalized)])$ID
#     DBs[i] <- index.DB(na.omit(normalized[, 2:ncol(normalized)]), cls, centrotypes="centroids")$DB
#     print(i)
# }
# 
# plot(c(3:12), DBs, xlab="Number of Clusters")
# lines(c(3:12), DBs)
# title("DB Index against K, GovCluster")

#RESULT: 5 or 7 (we go for 5 for now)
ks <- kmeans(na.omit(normalized[, 2:ncol(normalized)]), 5)
cls <- data.frame(ks$cluster)
row.names(cls) <- na.omit(normalized[, 2:ncol(normalized)])$ID
cls$ID <- row.names(cls)

hex_grid@data$ID <- as.character(hex_grid@data$ID)
hex_grid@data <- hex_grid@data %>% left_join(cls, by=c("ID"))


lnd <- SpatialPolygonsDataFrame(Sr = spTransform(hex_grid, CRSobj = CRS("+init=epsg:4326")), data = hex_grid@data)
lnd.f <- fortify(lnd)
lnd$id <- row.names(lnd)
lnd.f <- left_join(lnd.f, lnd@data, by=("id"))
lnd.f$ks.cluster <- as.factor(lnd.f$ks.cluster)

# Saving the hexagons in a geojson file.
writeOGR(hex_grid, "csv/car2go_gov_c5.geojson", layer="polygons", driver="GeoJSON", check_exists = FALSE)

map <- get_map(location = 'Washinton DC', zoom = 11, color = "bw")
mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group, fill=ks.cluster), data = lnd.f, color='black', alpha=0.9) + scale_fill_manual(values = c("red", "green", "blue", "yellow", "violet")) + ggtitle("Clusters (K=5), GovCluster")
mapPoints


# Signature for each cluster
cls$ID <- as.integer(cls$ID)
final <- normalized %>% left_join(cls, by=c("ID"))

write.table(final, "csv/car2go_gov_clusters.csv", row.names=F, col.names=F, sep=",")

c1 <- final[final$ks.cluster == 1,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 1 for Car2Go, GovCluster")

c1 <- final[final$ks.cluster == 2,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 2 for Car2Go, GovCluster")

c1 <- final[final$ks.cluster == 3,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1))  +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 3 for Car2Go, GovCluster")

c1 <- final[final$ks.cluster == 4,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 4 for Car2Go, GovCluster")


c1 <- final[final$ks.cluster == 5,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 5 for Car2Go, GovCluster")



```



# TaxAssessment Layer
```{r}
setwd("/Users/myeong/git/neighborhood-project/data/car2go/")

total <- read_delim("csv/car2go.csv", delim = ",",col_names = FALSE )
colnames(total) <- c("address", "engineType", "exterior", "fuel", "interior", "name", "smartPhoneRequired", "vin", "lon", "lat","date","time_mil")

total$ID <- row.names(total)
total$ID <- as.integer(total$ID)

gov_cluster <- readOGR("/Users/myeong/git/neighborhood-project/data/neighborhoods/dc_neighborhood_boundaries_GovTaxAssessment.kml", layer="dc_neighborhood_boundaries_GovTaxAssessment") %>% spTransform(CRS("+proj=longlat +datum=WGS84"))

map <- get_map(location = 'Washinton DC', zoom = 11, color = "bw")
mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group), data = gov_cluster, color='red', alpha=0) + ggtitle("Tax Assessment Layer")
mapPoints

xy <- total[,c("lon","lat")]
points <- SpatialPointsDataFrame(coords = xy, data = total,
                               proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))

points$month <- month(points$date)
points$day <- mday(points$date)
points$hour <- hour(points$date)
points <- points[!(points$month == 11 & points$day == 8 & points$hour == 7), ]

signature <- data.frame(matrix(ncol = 4, nrow = 0)) 
colnames(signature) <- c("time", "freq", "weekday", "id")

rm (total)
rm(xy)


for(i in 1:nrow(gov_cluster)) { 
  
  print(i)
  intersection = raster::intersect(x = points, y = gov_cluster[i,])
  if (nrow(intersection@data) == 0) next
  
  freq_table <- intersection@data %>% dplyr::group_by(date) %>% summarise(freq=n())
  freq_table$day <- c("Weekend", "Weekday", "Weekday", "Weekday", "Weekday", "Weekday", "Weekend")[as.POSIXlt(freq_table$date)$wday + 1]
  freq_table$day <- as.factor(freq_table$day)

  weekday <- freq_table[freq_table$day == "Weekday",]
  weekend <- freq_table[freq_table$day == "Weekend",]
  
  weekday$minute <- minute(weekday$date)/60
  weekday$minute[weekday$minute==0.6] <- 35/60
  weekday$time <- hour(weekday$date) + weekday$minute
  weekday <- weekday %>% dplyr::group_by(time) %>% summarise(freq = sum(freq), weekday=1)
  
  weekend$time <- hour(weekend$date) + minute(weekend$date)/60
  weekend <- weekend %>% dplyr::group_by(time) %>% summarise(freq = sum(freq), weekday=0)
    
  temp <- rbind(weekday, weekend)
  temp$id <- i 
  signature <- rbind(signature, temp)

}
write.csv(signature, file="csv/tax_5_min_signature_sum.csv")


## Since the loop takes a long time -- we're loading the result of the loop from a file
# signature <- read_delim("csv/5_min_signature_sum.csv", delim = ",",col_names = TRUE ) 
# signature <- signature[,-1]

hex_grid <- gov_cluster
row.names(hex_grid) <- as.character(1:length(hex_grid))
hex_grid$ID <- row.names(hex_grid)

# region-based time aggregation
time_agg <- signature %>% group_by(id) %>% summarise(freq = sum(freq)/576)
time_agg$id <- as.character(time_agg$id)

hex_grid@data <- hex_grid@data %>% left_join(time_agg, by = c("ID" = "id"))
hex_grid@data$freq[is.na(hex_grid@data$freq)] <- 0

lnd <- SpatialPolygonsDataFrame(Sr = spTransform(hex_grid, CRSobj = CRS("+init=epsg:4326")), data = hex_grid@data)
lnd.f <- fortify(lnd)
lnd$id <- row.names(lnd)
lnd.f <- left_join(lnd.f, lnd@data, by=("id"))
lnd.f$freq[lnd.f$freq == 0] <- 0.0001
# Need a basemap for this -- Density Map

map <- get_map(location = 'Washinton DC', zoom = 11, color = "bw")
mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group, fill=(freq)), data = lnd.f , alpha=0.9) + scale_fill_continuous(low = "yellow", high = "red") + ggtitle("Tax Assessment Layer")
mapPoints


# Conducting Clustering analysis for the Polygons
# Reshaping the dataframe to make signatures 
library(reshape)
sig_day <- signature[signature$weekday == 1,]
sig_end <- signature[signature$weekday == 0,]

day <- cast(sig_day, id~time, value="freq")
end <- cast(sig_end, id~time, value="freq")

day[is.na(day)] <- 0
end[is.na(end)] <- 0

day_norm <- as.data.frame(t(apply(day[,-1], 1, function(x)  (x-min(x))/(max(x)-min(x)) )))
end_norm <- as.data.frame(t(apply(end[,-1], 1, function(x)  (x-min(x))/(max(x)-min(x)) )))

#Reverting the graphs?
for (i in 1:nrow(day_norm)){
  day_norm[i,] <- apply(day_norm[i,], 1, function(x) 1-x)
}
for (i in 1:nrow(end_norm)){
  end_norm[i,] <- apply(day_norm[i,], 1, function(x) 1-x)
}

day_norm$id <- day$id
end_norm$id <- end$id

final <- data.frame(matrix(ncol=1, nrow=nrow(hex_grid@data)))
colnames(final) <- c ("ID")
final$ID <- c(1:nrow(hex_grid@data))
final <- final %>% left_join(day_norm, by = c("ID" = "id"))
final <- final %>% left_join(end_norm, by = c("ID" = "id"))

normalized <- final
normalized[is.na(normalized)] <- 0

DBs <- vector(mode="integer", length=10)
for (i in 1:10) {
    ks <- kmeans(na.omit(normalized[, 2:ncol(normalized)]), i+2)
    cls <- data.frame(ks$cluster)
    row.names(cls) <- na.omit(normalized[, 2:ncol(normalized)])$ID
    DBs[i] <- index.DB(na.omit(normalized[, 2:ncol(normalized)]), cls, centrotypes="centroids")$DB
    print(i)
}

plot(c(3:12), DBs, xlab="Number of Clusters")
lines(c(3:12), DBs)
title("DB Index against K, Tax Assessment")

#RESULT: 4
ks <- kmeans(na.omit(normalized[, 2:ncol(normalized)]), 4)
cls <- data.frame(ks$cluster)
row.names(cls) <- na.omit(normalized[, 2:ncol(normalized)])$ID
cls$ID <- row.names(cls)

hex_grid@data$ID <- as.character(hex_grid@data$ID)
hex_grid@data <- hex_grid@data %>% left_join(cls, by=c("ID"))


lnd <- SpatialPolygonsDataFrame(Sr = spTransform(hex_grid, CRSobj = CRS("+init=epsg:4326")), data = hex_grid@data)
lnd.f <- fortify(lnd)
lnd$id <- row.names(lnd)
lnd.f <- left_join(lnd.f, lnd@data, by=("id"))
lnd.f$ks.cluster <- as.factor(lnd.f$ks.cluster)

map <- get_map(location = 'Washinton DC', zoom = 11, color = "bw")
mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group, fill=ks.cluster), data = lnd.f, color='black', alpha=0.9) + scale_fill_manual(values = c("red", "green", "blue", "yellow", "violet")) + ggtitle("Clusters (K=4), TaxAssessment")
mapPoints


# Signature for each cluster
cls$ID <- as.integer(cls$ID)
final <- normalized %>% left_join(cls, by=c("ID"))

c1 <- final[final$ks.cluster == 1,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 1 for Car2Go, TaxAssessment")

c1 <- final[final$ks.cluster == 2,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 2 for Car2Go, TaxAssessment")

c1 <- final[final$ks.cluster == 3,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1))  +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 3 for Car2Go, TaxAssessment")

c1 <- final[final$ks.cluster == 4,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 4 for Car2Go, TaxAssessment")


c1 <- final[final$ks.cluster == 5,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 5 for Car2Go, TaxAssessment")



```



# DC Municipal Neighborhoods 
```{r}

total <- read_delim("csv/car2go.csv", delim = ",",col_names = FALSE )
colnames(total) <- c("address", "engineType", "exterior", "fuel", "interior", "name", "smartPhoneRequired", "vin", "lon", "lat","date","time_mil")

total$ID <- row.names(total)
total$ID <- as.integer(total$ID)

gov_cluster <- readOGR("/Users/myeong/git/neighborhood-project/data/neighborhoods/dc_neighborhood.geojson", "OGRGeoJSON") %>% spTransform(CRS("+proj=longlat +datum=WGS84"))

map <- get_map(location = 'Washinton DC', zoom = 11, color = "bw")
mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group), data = gov_cluster, color='red', alpha=0) + ggtitle("DC Municipal Neighborhoods")
mapPoints

xy <- total[,c("lon","lat")]
points <- SpatialPointsDataFrame(coords = xy, data = total,
                               proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))

points$month <- month(points$date)
points$day <- mday(points$date)
points$hour <- hour(points$date)
points <- points[!(points$month == 11 & points$day == 8 & points$hour == 7), ]

signature <- data.frame(matrix(ncol = 4, nrow = 0)) 
colnames(signature) <- c("time", "freq", "weekday", "id")

rm (total)
rm(xy)


for(i in 1:nrow(gov_cluster)) { 

  print(i)
  tryCatch({
    intersection = raster::intersect(x = points, y = gov_cluster[i,])
  }, error = function(err) {
    print(paste("ERROR:  ",err))    
    return(NULL)
  })
  
  if (nrow(intersection@data) == 0) next
  
  freq_table <- intersection@data %>% dplyr::group_by(date) %>% summarise(freq=n())
  freq_table$day <- c("Weekend", "Weekday", "Weekday", "Weekday", "Weekday", "Weekday", "Weekend")[as.POSIXlt(freq_table$date)$wday + 1]
  freq_table$day <- as.factor(freq_table$day)

  weekday <- freq_table[freq_table$day == "Weekday",]
  weekend <- freq_table[freq_table$day == "Weekend",]
  
  weekday$minute <- minute(weekday$date)/60
  weekday$minute[weekday$minute==0.6] <- 35/60
  weekday$time <- hour(weekday$date) + weekday$minute
  weekday <- weekday %>% dplyr::group_by(time) %>% summarise(freq = sum(freq), weekday=1)
  
  weekend$time <- hour(weekend$date) + minute(weekend$date)/60
  weekend <- weekend %>% dplyr::group_by(time) %>% summarise(freq = sum(freq), weekday=0)
    
  temp <- rbind(weekday, weekend)
  temp$id <- i 
  signature <- rbind(signature, temp)

}
write.csv(signature, file="csv/municipal_5_min_signature_sum.csv")


## Since the loop takes a long time -- we're loading the result of the loop from a file
# signature <- read_delim("csv/5_min_signature_sum.csv", delim = ",",col_names = TRUE ) 
# signature <- signature[,-1]

hex_grid <- gov_cluster
row.names(hex_grid) <- as.character(1:length(hex_grid))
hex_grid$ID <- row.names(hex_grid)

# region-based time aggregation
time_agg <- signature %>% group_by(id) %>% summarise(freq = sum(freq)/576)
time_agg$id <- as.character(time_agg$id)

hex_grid@data <- hex_grid@data %>% left_join(time_agg, by = c("ID" = "id"))
hex_grid@data$freq[is.na(hex_grid@data$freq)] <- 0

lnd <- SpatialPolygonsDataFrame(Sr = spTransform(hex_grid, CRSobj = CRS("+init=epsg:4326")), data = hex_grid@data)
lnd.f <- fortify(lnd)
lnd$id <- row.names(lnd)
lnd.f <- left_join(lnd.f, lnd@data, by=("id"))
lnd.f$freq[lnd.f$freq == 0] <- 0.0001
# Need a basemap for this -- Density Map

map <- get_map(location = 'Washinton DC', zoom = 11, color = "bw")
mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group, fill=(freq)), data = lnd.f , alpha=0.9) + scale_fill_continuous(low = "yellow", high = "red") + ggtitle("DC Municipal Neighborhoods")
mapPoints


# Conducting Clustering analysis for the Polygons
# Reshaping the dataframe to make signatures 
library(reshape)
sig_day <- signature[signature$weekday == 1,]
sig_end <- signature[signature$weekday == 0,]

day <- cast(sig_day, id~time, value="freq")
end <- cast(sig_end, id~time, value="freq")

day[is.na(day)] <- 0
end[is.na(end)] <- 0

day_norm <- as.data.frame(t(apply(day[,-1], 1, function(x)  (x-min(x))/(max(x)-min(x)) )))
end_norm <- as.data.frame(t(apply(end[,-1], 1, function(x)  (x-min(x))/(max(x)-min(x)) )))

#Reverting the graphs?
for (i in 1:nrow(day_norm)){
  day_norm[i,] <- apply(day_norm[i,], 1, function(x) 1-x)
}
for (i in 1:nrow(end_norm)){
  end_norm[i,] <- apply(day_norm[i,], 1, function(x) 1-x)
}

day_norm$id <- day$id
end_norm$id <- end$id

final <- data.frame(matrix(ncol=1, nrow=nrow(hex_grid@data)))
colnames(final) <- c ("ID")
final$ID <- c(1:nrow(hex_grid@data))
final <- final %>% left_join(day_norm, by = c("ID" = "id"))
final <- final %>% left_join(end_norm, by = c("ID" = "id"))

normalized <- final
normalized[is.na(normalized)] <- 0

DBs <- vector(mode="integer", length=10)
for (i in 1:10) {
    ks <- kmeans(na.omit(normalized[, 2:ncol(normalized)]), i+2)
    cls <- data.frame(ks$cluster)
    row.names(cls) <- na.omit(normalized[, 2:ncol(normalized)])$ID
    DBs[i] <- index.DB(na.omit(normalized[, 2:ncol(normalized)]), cls, centrotypes="centroids")$DB
    print(i)
}

plot(c(3:12), DBs, xlab="Number of Clusters")
lines(c(3:12), DBs)
title("DB Index against K, Tax Assessment")

#RESULT: 5
ks <- kmeans(na.omit(normalized[, 2:ncol(normalized)]), 4)
cls <- data.frame(ks$cluster)
row.names(cls) <- na.omit(normalized[, 2:ncol(normalized)])$ID
cls$ID <- row.names(cls)

hex_grid <- gov_cluster
row.names(hex_grid) <- as.character(1:length(hex_grid))
hex_grid$ID <- row.names(hex_grid)
hex_grid@data <- hex_grid@data %>% left_join(cls, by=c("ID"))

lnd <- SpatialPolygonsDataFrame(Sr = spTransform(hex_grid, CRSobj = CRS("+init=epsg:4326")), data = hex_grid@data)
lnd.f <- fortify(lnd)
lnd$id <- row.names(lnd)
lnd.f <- left_join(lnd.f, lnd@data, by=("id"))
lnd.f$ks.cluster <- as.factor(lnd.f$ks.cluster)

map <- get_map(location = 'Washinton DC', zoom = 11, color = "bw")
mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group, fill=ks.cluster), data = lnd.f, color='black', alpha=0.9) + scale_fill_manual(values = c("red", "green", "blue", "yellow", "violet")) + ggtitle("Clusters (K=4), DC Municipal Neighborhoods")
mapPoints


# Signature for each cluster
cls$ID <- as.integer(cls$ID)
final <- normalized %>% left_join(cls, by=c("ID"))

c1 <- final[final$ks.cluster == 1,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 1 for Car2Go, DC Municipal Neighborhoods")

c1 <- final[final$ks.cluster == 2,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 2 for Car2Go, DC Municipal Neighborhoods")

c1 <- final[final$ks.cluster == 3,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1))  +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 3 for Car2Go, DC Municipal Neighborhoods")

c1 <- final[final$ks.cluster == 4,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 4 for Car2Go, DC Municipal Neighborhoods")


c1 <- final[final$ks.cluster == 5,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 5 for Car2Go, DC Municipal Neighborhoods")


```




# Zillow
```{r}

total <- read_delim("csv/car2go.csv", delim = ",",col_names = FALSE )
colnames(total) <- c("address", "engineType", "exterior", "fuel", "interior", "name", "smartPhoneRequired", "vin", "lon", "lat","date","time_mil")

total$ID <- row.names(total)
total$ID <- as.integer(total$ID)

gov_cluster <- readOGR("/Users/myeong/git/neighborhood-project/data/neighborhoods/dc_neighborhood_boundaries_Zillow.kml", layer="dc_neighborhood_boundaries_Zillow") %>% spTransform(CRS("+proj=longlat +datum=WGS84"))

map <- get_map(location = 'Washinton DC', zoom = 11, color = "bw")
mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group), data = gov_cluster, color='red', alpha=0) + ggtitle("Zillow")
mapPoints

xy <- total[,c("lon","lat")]
points <- SpatialPointsDataFrame(coords = xy, data = total,
                               proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))

points$month <- month(points$date)
points$day <- mday(points$date)
points$hour <- hour(points$date)
points <- points[!(points$month == 11 & points$day == 8 & points$hour == 7), ]

signature <- data.frame(matrix(ncol = 4, nrow = 0)) 
colnames(signature) <- c("time", "freq", "weekday", "id")

rm (total)
rm(xy)


for(i in 1:nrow(gov_cluster)) { 

  print(i)
  tryCatch({
    intersection = raster::intersect(x = points, y = gov_cluster[i,])
  }, error = function(err) {
    print(paste("ERROR:  ",err))    
    return(NULL)
  })
  
  if (nrow(intersection@data) == 0) next
  
  freq_table <- intersection@data %>% dplyr::group_by(date) %>% summarise(freq=n())
  freq_table$day <- c("Weekend", "Weekday", "Weekday", "Weekday", "Weekday", "Weekday", "Weekend")[as.POSIXlt(freq_table$date)$wday + 1]
  freq_table$day <- as.factor(freq_table$day)

  weekday <- freq_table[freq_table$day == "Weekday",]
  weekend <- freq_table[freq_table$day == "Weekend",]
  
  weekday$minute <- minute(weekday$date)/60
  weekday$minute[weekday$minute==0.6] <- 35/60
  weekday$time <- hour(weekday$date) + weekday$minute
  weekday <- weekday %>% dplyr::group_by(time) %>% summarise(freq = sum(freq), weekday=1)
  
  weekend$time <- hour(weekend$date) + minute(weekend$date)/60
  weekend <- weekend %>% dplyr::group_by(time) %>% summarise(freq = sum(freq), weekday=0)
    
  temp <- rbind(weekday, weekend)
  temp$id <- i 
  signature <- rbind(signature, temp)

}
write.csv(signature, file="csv/zillow_5_min_signature_sum.csv")


## Since the loop takes a long time -- we're loading the result of the loop from a file
# signature <- read_delim("csv/5_min_signature_sum.csv", delim = ",",col_names = TRUE ) 
# signature <- signature[,-1]

hex_grid <- gov_cluster
row.names(hex_grid) <- as.character(1:length(hex_grid))
hex_grid$ID <- row.names(hex_grid)

# region-based time aggregation
time_agg <- signature %>% group_by(id) %>% summarise(freq = sum(freq)/576)
time_agg$id <- as.character(time_agg$id)

hex_grid@data <- hex_grid@data %>% left_join(time_agg, by = c("ID" = "id"))
hex_grid@data$freq[is.na(hex_grid@data$freq)] <- 0

lnd <- SpatialPolygonsDataFrame(Sr = spTransform(hex_grid, CRSobj = CRS("+init=epsg:4326")), data = hex_grid@data)
lnd.f <- fortify(lnd)
lnd$id <- row.names(lnd)
lnd.f <- left_join(lnd.f, lnd@data, by=("id"))
lnd.f$freq[lnd.f$freq == 0] <- 0.0001
# Need a basemap for this -- Density Map

map <- get_map(location = 'Washinton DC', zoom = 11, color = "bw")
mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group, fill=(freq)), data = lnd.f , alpha=0.9) + scale_fill_continuous(low = "yellow", high = "red") + ggtitle("Zillow")
mapPoints


# Conducting Clustering analysis for the Polygons
# Reshaping the dataframe to make signatures 
library(reshape)
sig_day <- signature[signature$weekday == 1,]
sig_end <- signature[signature$weekday == 0,]

day <- cast(sig_day, id~time, value="freq")
end <- cast(sig_end, id~time, value="freq")

day[is.na(day)] <- 0
end[is.na(end)] <- 0

day_norm <- as.data.frame(t(apply(day[,-1], 1, function(x)  (x-min(x))/(max(x)-min(x)) )))
end_norm <- as.data.frame(t(apply(end[,-1], 1, function(x)  (x-min(x))/(max(x)-min(x)) )))

#Reverting the graphs?
for (i in 1:nrow(day_norm)){
  day_norm[i,] <- apply(day_norm[i,], 1, function(x) 1-x)
}
for (i in 1:nrow(end_norm)){
  end_norm[i,] <- apply(day_norm[i,], 1, function(x) 1-x)
}

day_norm$id <- day$id
end_norm$id <- end$id

final <- data.frame(matrix(ncol=1, nrow=nrow(hex_grid@data)))
colnames(final) <- c ("ID")
final$ID <- c(1:nrow(hex_grid@data))
final <- final %>% left_join(day_norm, by = c("ID" = "id"))
final <- final %>% left_join(end_norm, by = c("ID" = "id"))

normalized <- final
normalized[is.na(normalized)] <- 0

DBs <- vector(mode="integer", length=10)
for (i in 1:10) {
    ks <- kmeans(na.omit(normalized[, 2:ncol(normalized)]), i+2)
    cls <- data.frame(ks$cluster)
    row.names(cls) <- na.omit(normalized[, 2:ncol(normalized)])$ID
    DBs[i] <- index.DB(na.omit(normalized[, 2:ncol(normalized)]), cls, centrotypes="centroids")$DB
    print(i)
}

plot(c(3:12), DBs, xlab="Number of Clusters")
lines(c(3:12), DBs)
title("DB Index against K, Zillow")

#RESULT: 5 
ks <- kmeans(na.omit(normalized[, 2:ncol(normalized)]), 5)
cls <- data.frame(ks$cluster)
row.names(cls) <- na.omit(normalized[, 2:ncol(normalized)])$ID
cls$ID <- row.names(cls)

hex_grid@data$ID <- as.character(hex_grid@data$ID)
hex_grid@data <- hex_grid@data %>% left_join(cls, by=c("ID"))


lnd <- SpatialPolygonsDataFrame(Sr = spTransform(hex_grid, CRSobj = CRS("+init=epsg:4326")), data = hex_grid@data)
lnd.f <- fortify(lnd)
lnd$id <- row.names(lnd)
lnd.f <- left_join(lnd.f, lnd@data, by=("id"))
lnd.f$ks.cluster <- as.factor(lnd.f$ks.cluster)

map <- get_map(location = 'Washinton DC', zoom = 11, color = "bw")
mapPoints <- ggmap(map) + geom_polygon(aes(x=long, y=lat, group=group, fill=ks.cluster), data = lnd.f, color='black', alpha=0.9) + scale_fill_manual(values = c("red", "green", "blue", "yellow", "violet")) + ggtitle("Clusters (K=5), Zillow")
mapPoints


# Signature for each cluster
cls$ID <- as.integer(cls$ID)
final <- normalized %>% left_join(cls, by=c("ID"))

c1 <- final[final$ks.cluster == 1,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 1 for Car2Go, Zillow")

c1 <- final[final$ks.cluster == 2,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 2 for Car2Go, Zillow")

c1 <- final[final$ks.cluster == 3,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1))  +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 3 for Car2Go, Zillow")

c1 <- final[final$ks.cluster == 4,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 4 for Car2Go, Zillow")


c1 <- final[final$ks.cluster == 5,]
c1 <- c1[,-1]
c1 <- c1[,-577]
c1 <- as.data.frame(apply(c1, 2, mean ))
colnames(c1) <- c("mean_freq")
c1$time <- c(1:576)
c1$day <- "Weekday"
c1[289:576,]$day <- "Weekend"
c1$day <- as.factor(c1$day)

ggplot(c1, aes(x = time, y = mean_freq, colour=(day), group = 1)) +
  geom_line() +
  geom_point(size = 1) + scale_y_continuous(limits=c(0, 1)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Average Frequency") + 
  xlab("Time with 5-minute Intervals") + ggtitle("Temporal Signature of Cluster 5 for Car2Go, Zillow")


```

